// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transmitter.proto

package gravity_api_transmitter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Method int32

const (
	Method_INSERT   Method = 0
	Method_UPDATE   Method = 1
	Method_DELETE   Method = 2
	Method_TRUNCATE Method = 3
)

var Method_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
	3: "TRUNCATE",
}

var Method_value = map[string]int32{
	"INSERT":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"TRUNCATE": 3,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{0}
}

type DataType int32

const (
	DataType_BOOLEAN DataType = 0
	DataType_BINARY  DataType = 1
	DataType_STRING  DataType = 2
	DataType_UINT64  DataType = 3
	DataType_INT64   DataType = 4
	DataType_FLOAT64 DataType = 5
	DataType_ARRAY   DataType = 6
	DataType_MAP     DataType = 7
)

var DataType_name = map[int32]string{
	0: "BOOLEAN",
	1: "BINARY",
	2: "STRING",
	3: "UINT64",
	4: "INT64",
	5: "FLOAT64",
	6: "ARRAY",
	7: "MAP",
}

var DataType_value = map[string]int32{
	"BOOLEAN": 0,
	"BINARY":  1,
	"STRING":  2,
	"UINT64":  3,
	"INT64":   4,
	"FLOAT64": 5,
	"ARRAY":   6,
	"MAP":     7,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{1}
}

type SendReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{0}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Record struct {
	EventName            string   `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Method               Method   `protobuf:"varint,3,opt,name=method,proto3,enum=gravity.api.transmitter.Method" json:"method,omitempty"`
	PrimaryKey           string   `protobuf:"bytes,4,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Record) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Record) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_INSERT
}

func (m *Record) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *Record) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value struct {
	Type                 DataType    `protobuf:"varint,1,opt,name=type,proto3,enum=gravity.api.transmitter.DataType" json:"type,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Map                  *MapValue   `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	Array                *ArrayValue `protobuf:"bytes,4,opt,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{3}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_BOOLEAN
}

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetMap() *MapValue {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *Value) GetArray() *ArrayValue {
	if m != nil {
		return m.Array
	}
	return nil
}

type MapValue struct {
	Fields               []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapValue) Reset()         { *m = MapValue{} }
func (m *MapValue) String() string { return proto.CompactTextString(m) }
func (*MapValue) ProtoMessage()    {}
func (*MapValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{4}
}

func (m *MapValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapValue.Unmarshal(m, b)
}
func (m *MapValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapValue.Marshal(b, m, deterministic)
}
func (m *MapValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapValue.Merge(m, src)
}
func (m *MapValue) XXX_Size() int {
	return xxx_messageInfo_MapValue.Size(m)
}
func (m *MapValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MapValue.DiscardUnknown(m)
}

var xxx_messageInfo_MapValue proto.InternalMessageInfo

func (m *MapValue) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ArrayValue struct {
	Elements             []*Value `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayValue) Reset()         { *m = ArrayValue{} }
func (m *ArrayValue) String() string { return proto.CompactTextString(m) }
func (*ArrayValue) ProtoMessage()    {}
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{5}
}

func (m *ArrayValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayValue.Unmarshal(m, b)
}
func (m *ArrayValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayValue.Marshal(b, m, deterministic)
}
func (m *ArrayValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayValue.Merge(m, src)
}
func (m *ArrayValue) XXX_Size() int {
	return xxx_messageInfo_ArrayValue.Size(m)
}
func (m *ArrayValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayValue.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayValue proto.InternalMessageInfo

func (m *ArrayValue) GetElements() []*Value {
	if m != nil {
		return m.Elements
	}
	return nil
}

type TruncateRequest struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateRequest) Reset()         { *m = TruncateRequest{} }
func (m *TruncateRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateRequest) ProtoMessage()    {}
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{6}
}

func (m *TruncateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateRequest.Unmarshal(m, b)
}
func (m *TruncateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateRequest.Marshal(b, m, deterministic)
}
func (m *TruncateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateRequest.Merge(m, src)
}
func (m *TruncateRequest) XXX_Size() int {
	return xxx_messageInfo_TruncateRequest.Size(m)
}
func (m *TruncateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateRequest proto.InternalMessageInfo

func (m *TruncateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type TruncateReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateReply) Reset()         { *m = TruncateReply{} }
func (m *TruncateReply) String() string { return proto.CompactTextString(m) }
func (*TruncateReply) ProtoMessage()    {}
func (*TruncateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2827fe02ce03bde9, []int{7}
}

func (m *TruncateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateReply.Unmarshal(m, b)
}
func (m *TruncateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateReply.Marshal(b, m, deterministic)
}
func (m *TruncateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateReply.Merge(m, src)
}
func (m *TruncateReply) XXX_Size() int {
	return xxx_messageInfo_TruncateReply.Size(m)
}
func (m *TruncateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateReply.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateReply proto.InternalMessageInfo

func (m *TruncateReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TruncateReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterEnum("gravity.api.transmitter.Method", Method_name, Method_value)
	proto.RegisterEnum("gravity.api.transmitter.DataType", DataType_name, DataType_value)
	proto.RegisterType((*SendReply)(nil), "gravity.api.transmitter.SendReply")
	proto.RegisterType((*Record)(nil), "gravity.api.transmitter.Record")
	proto.RegisterType((*Field)(nil), "gravity.api.transmitter.Field")
	proto.RegisterType((*Value)(nil), "gravity.api.transmitter.Value")
	proto.RegisterType((*MapValue)(nil), "gravity.api.transmitter.MapValue")
	proto.RegisterType((*ArrayValue)(nil), "gravity.api.transmitter.ArrayValue")
	proto.RegisterType((*TruncateRequest)(nil), "gravity.api.transmitter.TruncateRequest")
	proto.RegisterType((*TruncateReply)(nil), "gravity.api.transmitter.TruncateReply")
}

func init() { proto.RegisterFile("transmitter.proto", fileDescriptor_2827fe02ce03bde9) }

var fileDescriptor_2827fe02ce03bde9 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xeb, 0xd8, 0x71, 0x26, 0xa5, 0x98, 0x11, 0x02, 0xab, 0x42, 0x25, 0x18, 0x09, 0xa2,
	0x1e, 0x72, 0x48, 0x4b, 0x11, 0x95, 0x38, 0x38, 0xc4, 0x85, 0x88, 0xc4, 0x29, 0x1b, 0x17, 0xa9,
	0x17, 0xa4, 0x6d, 0xb2, 0x94, 0x48, 0xb1, 0x63, 0xec, 0x4d, 0x24, 0xff, 0x37, 0x8e, 0x5c, 0xf9,
	0x4f, 0x68, 0x77, 0x9d, 0x3a, 0x42, 0x32, 0x5f, 0xb7, 0x99, 0xf1, 0x7b, 0xcf, 0xb3, 0x6f, 0x67,
	0x16, 0xee, 0xf1, 0x94, 0xc6, 0x59, 0x34, 0xe7, 0x9c, 0xa5, 0x9d, 0x24, 0x5d, 0xf2, 0x25, 0x3e,
	0xbc, 0x49, 0xe9, 0x7a, 0xce, 0xf3, 0x0e, 0x4d, 0xe6, 0x9d, 0xad, 0xcf, 0xee, 0x6b, 0x68, 0x4c,
	0x58, 0x3c, 0x23, 0x2c, 0x59, 0xe4, 0xe8, 0x40, 0x3d, 0x5b, 0x4d, 0xa7, 0x2c, 0xcb, 0x1c, 0xad,
	0xa5, 0xb5, 0x2d, 0xb2, 0x49, 0xf1, 0x01, 0x98, 0x29, 0xa3, 0xd9, 0x32, 0x76, 0x76, 0x5b, 0x5a,
	0xbb, 0x41, 0x8a, 0xcc, 0xfd, 0xa1, 0x81, 0x49, 0xd8, 0x74, 0x99, 0xce, 0xf0, 0x11, 0x34, 0xd8,
	0x9a, 0xc5, 0x3c, 0xa0, 0x11, 0x93, 0xf4, 0x06, 0x29, 0x0b, 0x78, 0x1f, 0x0c, 0x4e, 0xaf, 0x17,
	0xac, 0xe0, 0xab, 0x04, 0x5f, 0x82, 0x19, 0x31, 0xfe, 0x65, 0x39, 0x73, 0xf4, 0x96, 0xd6, 0xde,
	0xef, 0x3e, 0xee, 0x54, 0xf4, 0xd9, 0x19, 0x49, 0x18, 0x29, 0xe0, 0x78, 0x08, 0x90, 0xa4, 0xf3,
	0x88, 0xa6, 0xf9, 0x7b, 0x96, 0x3b, 0x35, 0xa9, 0xb9, 0x55, 0xc1, 0x53, 0x30, 0x3f, 0xcf, 0xd9,
	0x62, 0x96, 0x39, 0x46, 0x4b, 0x6f, 0x37, 0xbb, 0x87, 0x95, 0xc2, 0xe7, 0x02, 0x46, 0x0a, 0xb4,
	0xfb, 0x01, 0x0c, 0x59, 0x40, 0x84, 0x5a, 0x5c, 0x1e, 0x44, 0xc6, 0x78, 0x02, 0xc6, 0x9a, 0x2e,
	0x56, 0x4c, 0x36, 0xfb, 0x3b, 0xcd, 0x8f, 0x02, 0x45, 0x14, 0xd8, 0xfd, 0xae, 0x81, 0x21, 0x0b,
	0xf8, 0x02, 0x6a, 0x3c, 0x4f, 0x94, 0xe6, 0x7e, 0xf7, 0x49, 0x25, 0xbd, 0x4f, 0x39, 0x0d, 0xf3,
	0x84, 0x11, 0x09, 0x17, 0xd6, 0xa9, 0xdf, 0x0a, 0xeb, 0xf6, 0x0a, 0x59, 0x3c, 0x06, 0x3d, 0xa2,
	0x49, 0xd1, 0x4a, 0xb5, 0xd6, 0x88, 0x26, 0xaa, 0x1b, 0x81, 0xc6, 0x57, 0x60, 0xd0, 0x34, 0xa5,
	0xca, 0xb1, 0x66, 0xf7, 0x69, 0x25, 0xcd, 0x13, 0xa8, 0xe2, 0x18, 0x92, 0xe1, 0xf6, 0xc0, 0xda,
	0x68, 0x6d, 0xb9, 0xab, 0xfd, 0x93, 0xbb, 0xef, 0x00, 0x4a, 0x61, 0x3c, 0x03, 0x8b, 0x2d, 0x58,
	0xc4, 0x62, 0xfe, 0x67, 0x1d, 0xd5, 0xca, 0x2d, 0xde, 0x7d, 0x0e, 0x77, 0xc3, 0x74, 0x15, 0x4f,
	0x29, 0x67, 0x84, 0x7d, 0x5d, 0xb1, 0x8c, 0x97, 0x13, 0xa6, 0x6d, 0x4d, 0x98, 0xeb, 0xc1, 0x9d,
	0x12, 0xf8, 0x5f, 0x33, 0x7e, 0x74, 0x06, 0xa6, 0x9a, 0x3e, 0x04, 0x30, 0x07, 0xc1, 0xc4, 0x27,
	0xa1, 0xbd, 0x23, 0xe2, 0xcb, 0x8b, 0xbe, 0x17, 0xfa, 0xb6, 0x26, 0xe2, 0xbe, 0x3f, 0xf4, 0x43,
	0xdf, 0xde, 0xc5, 0x3d, 0xb0, 0x42, 0x72, 0x19, 0xbc, 0x11, 0x5f, 0xf4, 0xa3, 0x1b, 0xb0, 0x36,
	0xb7, 0x89, 0x4d, 0xa8, 0xf7, 0xc6, 0xe3, 0xa1, 0xef, 0x05, 0x8a, 0xde, 0x1b, 0x04, 0x1e, 0xb9,
	0x52, 0xf4, 0x49, 0x48, 0x06, 0xc1, 0x5b, 0x7b, 0x57, 0xca, 0x0e, 0x82, 0xf0, 0xf4, 0xc4, 0xd6,
	0xb1, 0x01, 0x86, 0x0a, 0x6b, 0x82, 0x7b, 0x3e, 0x1c, 0x7b, 0x22, 0x31, 0x44, 0xdd, 0x23, 0xc4,
	0xbb, 0xb2, 0x4d, 0xac, 0x83, 0x3e, 0xf2, 0x2e, 0xec, 0x7a, 0xf7, 0x9b, 0x06, 0xcd, 0xb0, 0x34,
	0x0c, 0x47, 0x50, 0x13, 0x7b, 0x8d, 0xd5, 0x1b, 0xa5, 0xd6, 0xf6, 0xc0, 0xad, 0x04, 0xdc, 0xbe,
	0x0b, 0xee, 0x0e, 0x7e, 0x02, 0x6b, 0x63, 0x23, 0xb6, 0x2b, 0x19, 0xbf, 0x5c, 0xc9, 0xc1, 0xb3,
	0xbf, 0x40, 0x4a, 0xfd, 0x6b, 0x53, 0x3e, 0x53, 0xc7, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x33,
	0xa1, 0x99, 0x08, 0xbb, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransmitterClient is the client API for Transmitter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransmitterClient interface {
	Send(ctx context.Context, in *Record, opts ...grpc.CallOption) (*SendReply, error)
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateReply, error)
}

type transmitterClient struct {
	cc *grpc.ClientConn
}

func NewTransmitterClient(cc *grpc.ClientConn) TransmitterClient {
	return &transmitterClient{cc}
}

func (c *transmitterClient) Send(ctx context.Context, in *Record, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/gravity.api.transmitter.Transmitter/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transmitterClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateReply, error) {
	out := new(TruncateReply)
	err := c.cc.Invoke(ctx, "/gravity.api.transmitter.Transmitter/Truncate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransmitterServer is the server API for Transmitter service.
type TransmitterServer interface {
	Send(context.Context, *Record) (*SendReply, error)
	Truncate(context.Context, *TruncateRequest) (*TruncateReply, error)
}

// UnimplementedTransmitterServer can be embedded to have forward compatible implementations.
type UnimplementedTransmitterServer struct {
}

func (*UnimplementedTransmitterServer) Send(ctx context.Context, req *Record) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedTransmitterServer) Truncate(ctx context.Context, req *TruncateRequest) (*TruncateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Truncate not implemented")
}

func RegisterTransmitterServer(s *grpc.Server, srv TransmitterServer) {
	s.RegisterService(&_Transmitter_serviceDesc, srv)
}

func _Transmitter_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmitterServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.transmitter.Transmitter/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmitterServer).Send(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transmitter_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmitterServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.transmitter.Transmitter/Truncate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmitterServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transmitter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.api.transmitter.Transmitter",
	HandlerType: (*TransmitterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Transmitter_Send_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _Transmitter_Truncate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transmitter.proto",
}
