// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package gravity_api_controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetClientCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientCountRequest) Reset()         { *m = GetClientCountRequest{} }
func (m *GetClientCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientCountRequest) ProtoMessage()    {}
func (*GetClientCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *GetClientCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientCountRequest.Unmarshal(m, b)
}
func (m *GetClientCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientCountRequest.Marshal(b, m, deterministic)
}
func (m *GetClientCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientCountRequest.Merge(m, src)
}
func (m *GetClientCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientCountRequest.Size(m)
}
func (m *GetClientCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientCountRequest proto.InternalMessageInfo

type GetClientCountReply struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientCountReply) Reset()         { *m = GetClientCountReply{} }
func (m *GetClientCountReply) String() string { return proto.CompactTextString(m) }
func (*GetClientCountReply) ProtoMessage()    {}
func (*GetClientCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *GetClientCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientCountReply.Unmarshal(m, b)
}
func (m *GetClientCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientCountReply.Marshal(b, m, deterministic)
}
func (m *GetClientCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientCountReply.Merge(m, src)
}
func (m *GetClientCountReply) XXX_Size() int {
	return xxx_messageInfo_GetClientCountReply.Size(m)
}
func (m *GetClientCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientCountReply proto.InternalMessageInfo

func (m *GetClientCountReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetPipelineCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelineCountRequest) Reset()         { *m = GetPipelineCountRequest{} }
func (m *GetPipelineCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelineCountRequest) ProtoMessage()    {}
func (*GetPipelineCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *GetPipelineCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineCountRequest.Unmarshal(m, b)
}
func (m *GetPipelineCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineCountRequest.Marshal(b, m, deterministic)
}
func (m *GetPipelineCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineCountRequest.Merge(m, src)
}
func (m *GetPipelineCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelineCountRequest.Size(m)
}
func (m *GetPipelineCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineCountRequest proto.InternalMessageInfo

type GetPipelineCountReply struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelineCountReply) Reset()         { *m = GetPipelineCountReply{} }
func (m *GetPipelineCountReply) String() string { return proto.CompactTextString(m) }
func (*GetPipelineCountReply) ProtoMessage()    {}
func (*GetPipelineCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *GetPipelineCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineCountReply.Unmarshal(m, b)
}
func (m *GetPipelineCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineCountReply.Marshal(b, m, deterministic)
}
func (m *GetPipelineCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineCountReply.Merge(m, src)
}
func (m *GetPipelineCountReply) XXX_Size() int {
	return xxx_messageInfo_GetPipelineCountReply.Size(m)
}
func (m *GetPipelineCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineCountReply proto.InternalMessageInfo

func (m *GetPipelineCountReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RegisterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type RegisterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{5}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type UnregisterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterRequest) Reset()         { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()    {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{6}
}

func (m *UnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRequest.Unmarshal(m, b)
}
func (m *UnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRequest.Merge(m, src)
}
func (m *UnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterRequest.Size(m)
}
func (m *UnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRequest proto.InternalMessageInfo

func (m *UnregisterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type UnregisterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterReply) Reset()         { *m = UnregisterReply{} }
func (m *UnregisterReply) String() string { return proto.CompactTextString(m) }
func (*UnregisterReply) ProtoMessage()    {}
func (*UnregisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{7}
}

func (m *UnregisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterReply.Unmarshal(m, b)
}
func (m *UnregisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterReply.Marshal(b, m, deterministic)
}
func (m *UnregisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterReply.Merge(m, src)
}
func (m *UnregisterReply) XXX_Size() int {
	return xxx_messageInfo_UnregisterReply.Size(m)
}
func (m *UnregisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterReply proto.InternalMessageInfo

func (m *UnregisterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UnregisterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ReleasePipelinesRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Pipelines            []uint64 `protobuf:"varint,2,rep,packed,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasePipelinesRequest) Reset()         { *m = ReleasePipelinesRequest{} }
func (m *ReleasePipelinesRequest) String() string { return proto.CompactTextString(m) }
func (*ReleasePipelinesRequest) ProtoMessage()    {}
func (*ReleasePipelinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{8}
}

func (m *ReleasePipelinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasePipelinesRequest.Unmarshal(m, b)
}
func (m *ReleasePipelinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasePipelinesRequest.Marshal(b, m, deterministic)
}
func (m *ReleasePipelinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasePipelinesRequest.Merge(m, src)
}
func (m *ReleasePipelinesRequest) XXX_Size() int {
	return xxx_messageInfo_ReleasePipelinesRequest.Size(m)
}
func (m *ReleasePipelinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasePipelinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasePipelinesRequest proto.InternalMessageInfo

func (m *ReleasePipelinesRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ReleasePipelinesRequest) GetPipelines() []uint64 {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type ReleasePipelinesReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasePipelinesReply) Reset()         { *m = ReleasePipelinesReply{} }
func (m *ReleasePipelinesReply) String() string { return proto.CompactTextString(m) }
func (*ReleasePipelinesReply) ProtoMessage()    {}
func (*ReleasePipelinesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{9}
}

func (m *ReleasePipelinesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasePipelinesReply.Unmarshal(m, b)
}
func (m *ReleasePipelinesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasePipelinesReply.Marshal(b, m, deterministic)
}
func (m *ReleasePipelinesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasePipelinesReply.Merge(m, src)
}
func (m *ReleasePipelinesReply) XXX_Size() int {
	return xxx_messageInfo_ReleasePipelinesReply.Size(m)
}
func (m *ReleasePipelinesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasePipelinesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasePipelinesReply proto.InternalMessageInfo

func (m *ReleasePipelinesReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReleasePipelinesReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type AssignPipelineRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	PipelineID           uint64   `protobuf:"varint,2,opt,name=pipelineID,proto3" json:"pipelineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignPipelineRequest) Reset()         { *m = AssignPipelineRequest{} }
func (m *AssignPipelineRequest) String() string { return proto.CompactTextString(m) }
func (*AssignPipelineRequest) ProtoMessage()    {}
func (*AssignPipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{10}
}

func (m *AssignPipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignPipelineRequest.Unmarshal(m, b)
}
func (m *AssignPipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignPipelineRequest.Marshal(b, m, deterministic)
}
func (m *AssignPipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignPipelineRequest.Merge(m, src)
}
func (m *AssignPipelineRequest) XXX_Size() int {
	return xxx_messageInfo_AssignPipelineRequest.Size(m)
}
func (m *AssignPipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignPipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignPipelineRequest proto.InternalMessageInfo

func (m *AssignPipelineRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AssignPipelineRequest) GetPipelineID() uint64 {
	if m != nil {
		return m.PipelineID
	}
	return 0
}

type AssignPipelineReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignPipelineReply) Reset()         { *m = AssignPipelineReply{} }
func (m *AssignPipelineReply) String() string { return proto.CompactTextString(m) }
func (*AssignPipelineReply) ProtoMessage()    {}
func (*AssignPipelineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{11}
}

func (m *AssignPipelineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignPipelineReply.Unmarshal(m, b)
}
func (m *AssignPipelineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignPipelineReply.Marshal(b, m, deterministic)
}
func (m *AssignPipelineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignPipelineReply.Merge(m, src)
}
func (m *AssignPipelineReply) XXX_Size() int {
	return xxx_messageInfo_AssignPipelineReply.Size(m)
}
func (m *AssignPipelineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignPipelineReply.DiscardUnknown(m)
}

var xxx_messageInfo_AssignPipelineReply proto.InternalMessageInfo

func (m *AssignPipelineReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AssignPipelineReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RevokePipelineRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	PipelineID           uint64   `protobuf:"varint,2,opt,name=pipelineID,proto3" json:"pipelineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePipelineRequest) Reset()         { *m = RevokePipelineRequest{} }
func (m *RevokePipelineRequest) String() string { return proto.CompactTextString(m) }
func (*RevokePipelineRequest) ProtoMessage()    {}
func (*RevokePipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{12}
}

func (m *RevokePipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePipelineRequest.Unmarshal(m, b)
}
func (m *RevokePipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePipelineRequest.Marshal(b, m, deterministic)
}
func (m *RevokePipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePipelineRequest.Merge(m, src)
}
func (m *RevokePipelineRequest) XXX_Size() int {
	return xxx_messageInfo_RevokePipelineRequest.Size(m)
}
func (m *RevokePipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePipelineRequest proto.InternalMessageInfo

func (m *RevokePipelineRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RevokePipelineRequest) GetPipelineID() uint64 {
	if m != nil {
		return m.PipelineID
	}
	return 0
}

type RevokePipelineReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePipelineReply) Reset()         { *m = RevokePipelineReply{} }
func (m *RevokePipelineReply) String() string { return proto.CompactTextString(m) }
func (*RevokePipelineReply) ProtoMessage()    {}
func (*RevokePipelineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{13}
}

func (m *RevokePipelineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePipelineReply.Unmarshal(m, b)
}
func (m *RevokePipelineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePipelineReply.Marshal(b, m, deterministic)
}
func (m *RevokePipelineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePipelineReply.Merge(m, src)
}
func (m *RevokePipelineReply) XXX_Size() int {
	return xxx_messageInfo_RevokePipelineReply.Size(m)
}
func (m *RevokePipelineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePipelineReply.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePipelineReply proto.InternalMessageInfo

func (m *RevokePipelineReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RevokePipelineReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*GetClientCountRequest)(nil), "gravity.api.controller.GetClientCountRequest")
	proto.RegisterType((*GetClientCountReply)(nil), "gravity.api.controller.GetClientCountReply")
	proto.RegisterType((*GetPipelineCountRequest)(nil), "gravity.api.controller.GetPipelineCountRequest")
	proto.RegisterType((*GetPipelineCountReply)(nil), "gravity.api.controller.GetPipelineCountReply")
	proto.RegisterType((*RegisterRequest)(nil), "gravity.api.controller.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "gravity.api.controller.RegisterReply")
	proto.RegisterType((*UnregisterRequest)(nil), "gravity.api.controller.UnregisterRequest")
	proto.RegisterType((*UnregisterReply)(nil), "gravity.api.controller.UnregisterReply")
	proto.RegisterType((*ReleasePipelinesRequest)(nil), "gravity.api.controller.ReleasePipelinesRequest")
	proto.RegisterType((*ReleasePipelinesReply)(nil), "gravity.api.controller.ReleasePipelinesReply")
	proto.RegisterType((*AssignPipelineRequest)(nil), "gravity.api.controller.AssignPipelineRequest")
	proto.RegisterType((*AssignPipelineReply)(nil), "gravity.api.controller.AssignPipelineReply")
	proto.RegisterType((*RevokePipelineRequest)(nil), "gravity.api.controller.RevokePipelineRequest")
	proto.RegisterType((*RevokePipelineReply)(nil), "gravity.api.controller.RevokePipelineReply")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x51, 0x4b, 0xc2, 0x50,
	0x14, 0xc7, 0xd5, 0x96, 0xe9, 0x81, 0xd2, 0xae, 0xa9, 0x6b, 0x44, 0xc8, 0x85, 0xd0, 0x90, 0x4d,
	0xa8, 0x4f, 0x20, 0x13, 0xc4, 0xb7, 0xb8, 0xd1, 0x5b, 0x2f, 0x73, 0x1c, 0x64, 0x34, 0xee, 0xd6,
	0xee, 0x55, 0xf0, 0x2b, 0xf5, 0x29, 0xc3, 0xe9, 0x9c, 0xce, 0xad, 0xd6, 0xe8, 0xf1, 0xdc, 0xf3,
	0x3f, 0xff, 0xf3, 0xe7, 0xc0, 0xef, 0x42, 0xd3, 0xf6, 0xb8, 0x0c, 0x3c, 0xd7, 0xc5, 0xc0, 0xf0,
	0x03, 0x4f, 0x7a, 0xa4, 0xb3, 0x08, 0xac, 0x95, 0x23, 0xd7, 0x86, 0xe5, 0x3b, 0x46, 0xdc, 0xa5,
	0x5d, 0x68, 0x4f, 0x51, 0x9a, 0xae, 0x83, 0x5c, 0x9a, 0xde, 0x92, 0x4b, 0x86, 0x9f, 0x4b, 0x14,
	0x92, 0x0e, 0xa1, 0x95, 0x6c, 0xf8, 0xee, 0x9a, 0xdc, 0xc0, 0xb9, 0xbd, 0xa9, 0xd4, 0x72, 0xaf,
	0x3c, 0x50, 0xd8, 0xb6, 0xa0, 0xb7, 0xd0, 0x9d, 0xa2, 0x7c, 0x71, 0x7c, 0x74, 0x1d, 0x8e, 0x47,
	0x3e, 0x7a, 0xb8, 0x20, 0xd1, 0xca, 0x76, 0xd2, 0xa1, 0xc1, 0x70, 0xe1, 0x08, 0x89, 0xc1, 0xce,
	0x81, 0x68, 0x50, 0xb3, 0xc3, 0x18, 0xb3, 0x49, 0xa8, 0xad, 0xb3, 0x7d, 0x4d, 0xc7, 0x70, 0x19,
	0xcb, 0x37, 0xae, 0x2a, 0x5c, 0x88, 0xa5, 0x6d, 0xa3, 0x10, 0xa1, 0xb6, 0xc6, 0xa2, 0x92, 0x74,
	0xa0, 0x1a, 0xa0, 0x25, 0x3c, 0xae, 0x56, 0x42, 0x93, 0x5d, 0x45, 0x47, 0x70, 0xfd, 0xc6, 0x83,
	0x3f, 0xec, 0x34, 0xa1, 0x71, 0x38, 0x50, 0x6c, 0xeb, 0x2b, 0x74, 0x19, 0xba, 0x68, 0x09, 0x8c,
	0x4e, 0x23, 0x72, 0xec, 0x26, 0x77, 0x50, 0xf7, 0x23, 0xbd, 0x5a, 0xe9, 0x9d, 0x0d, 0x14, 0x16,
	0x3f, 0xd0, 0x19, 0xb4, 0x4f, 0x4d, 0x8b, 0xe6, 0x6b, 0x8f, 0x85, 0x70, 0x16, 0x3c, 0x72, 0xca,
	0x93, 0xee, 0x1e, 0x20, 0x0a, 0x33, 0x9b, 0x84, 0x86, 0x0a, 0x3b, 0x78, 0xa1, 0x53, 0x68, 0x25,
	0x4d, 0x0b, 0xa7, 0x63, 0xb8, 0xf2, 0x3e, 0xf0, 0x9f, 0xd3, 0x25, 0x4d, 0x0b, 0xa5, 0x7b, 0xfa,
	0x52, 0x00, 0xcc, 0x3d, 0x62, 0x84, 0xc3, 0xd5, 0x31, 0x49, 0x44, 0x37, 0xd2, 0x69, 0x34, 0x52,
	0x51, 0xd4, 0x86, 0x79, 0xe5, 0xbe, 0xbb, 0xa6, 0x25, 0x22, 0xa1, 0x99, 0x24, 0x8e, 0x8c, 0x7e,
	0xb0, 0x48, 0xc3, 0x56, 0xd3, 0xf3, 0x0f, 0x6c, 0xb7, 0xbe, 0x43, 0x2d, 0x22, 0x91, 0xf4, 0xb3,
	0x86, 0x13, 0x68, 0x6b, 0x0f, 0xbf, 0x0b, 0xb7, 0xee, 0x73, 0x80, 0x98, 0x39, 0xf2, 0x98, 0x35,
	0x76, 0x02, 0xb2, 0xd6, 0xcf, 0x23, 0xdd, 0xdf, 0x2d, 0x49, 0x4f, 0xf6, 0xdd, 0x32, 0xe0, 0xcd,
	0xbe, 0x5b, 0x2a, 0x98, 0xb4, 0x34, 0xaf, 0x86, 0xff, 0xf3, 0xf3, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe7, 0x30, 0x77, 0x6c, 0xb3, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	GetClientCount(ctx context.Context, in *GetClientCountRequest, opts ...grpc.CallOption) (*GetClientCountReply, error)
	GetPipelineCount(ctx context.Context, in *GetPipelineCountRequest, opts ...grpc.CallOption) (*GetPipelineCountReply, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterReply, error)
	ReleasePipelines(ctx context.Context, in *ReleasePipelinesRequest, opts ...grpc.CallOption) (*ReleasePipelinesReply, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) GetClientCount(ctx context.Context, in *GetClientCountRequest, opts ...grpc.CallOption) (*GetClientCountReply, error) {
	out := new(GetClientCountReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/GetClientCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetPipelineCount(ctx context.Context, in *GetPipelineCountRequest, opts ...grpc.CallOption) (*GetPipelineCountReply, error) {
	out := new(GetPipelineCountReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/GetPipelineCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterReply, error) {
	out := new(UnregisterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReleasePipelines(ctx context.Context, in *ReleasePipelinesRequest, opts ...grpc.CallOption) (*ReleasePipelinesReply, error) {
	out := new(ReleasePipelinesReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/ReleasePipelines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	GetClientCount(context.Context, *GetClientCountRequest) (*GetClientCountReply, error)
	GetPipelineCount(context.Context, *GetPipelineCountRequest) (*GetPipelineCountReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Unregister(context.Context, *UnregisterRequest) (*UnregisterReply, error)
	ReleasePipelines(context.Context, *ReleasePipelinesRequest) (*ReleasePipelinesReply, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) GetClientCount(ctx context.Context, req *GetClientCountRequest) (*GetClientCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientCount not implemented")
}
func (*UnimplementedControllerServer) GetPipelineCount(ctx context.Context, req *GetPipelineCountRequest) (*GetPipelineCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineCount not implemented")
}
func (*UnimplementedControllerServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedControllerServer) Unregister(ctx context.Context, req *UnregisterRequest) (*UnregisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (*UnimplementedControllerServer) ReleasePipelines(ctx context.Context, req *ReleasePipelinesRequest) (*ReleasePipelinesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleasePipelines not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_GetClientCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetClientCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/GetClientCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetClientCount(ctx, req.(*GetClientCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetPipelineCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetPipelineCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/GetPipelineCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetPipelineCount(ctx, req.(*GetPipelineCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ReleasePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ReleasePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/ReleasePipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ReleasePipelines(ctx, req.(*ReleasePipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.api.controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientCount",
			Handler:    _Controller_GetClientCount_Handler,
		},
		{
			MethodName: "GetPipelineCount",
			Handler:    _Controller_GetPipelineCount_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Controller_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Controller_Unregister_Handler,
		},
		{
			MethodName: "ReleasePipelines",
			Handler:    _Controller_ReleasePipelines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
