// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package gravity_api_controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetClientCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientCountRequest) Reset()         { *m = GetClientCountRequest{} }
func (m *GetClientCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientCountRequest) ProtoMessage()    {}
func (*GetClientCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *GetClientCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientCountRequest.Unmarshal(m, b)
}
func (m *GetClientCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientCountRequest.Marshal(b, m, deterministic)
}
func (m *GetClientCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientCountRequest.Merge(m, src)
}
func (m *GetClientCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientCountRequest.Size(m)
}
func (m *GetClientCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientCountRequest proto.InternalMessageInfo

type GetClientCountReply struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientCountReply) Reset()         { *m = GetClientCountReply{} }
func (m *GetClientCountReply) String() string { return proto.CompactTextString(m) }
func (*GetClientCountReply) ProtoMessage()    {}
func (*GetClientCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *GetClientCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientCountReply.Unmarshal(m, b)
}
func (m *GetClientCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientCountReply.Marshal(b, m, deterministic)
}
func (m *GetClientCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientCountReply.Merge(m, src)
}
func (m *GetClientCountReply) XXX_Size() int {
	return xxx_messageInfo_GetClientCountReply.Size(m)
}
func (m *GetClientCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientCountReply proto.InternalMessageInfo

func (m *GetClientCountReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetPipelineCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelineCountRequest) Reset()         { *m = GetPipelineCountRequest{} }
func (m *GetPipelineCountRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelineCountRequest) ProtoMessage()    {}
func (*GetPipelineCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{2}
}

func (m *GetPipelineCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineCountRequest.Unmarshal(m, b)
}
func (m *GetPipelineCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineCountRequest.Marshal(b, m, deterministic)
}
func (m *GetPipelineCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineCountRequest.Merge(m, src)
}
func (m *GetPipelineCountRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelineCountRequest.Size(m)
}
func (m *GetPipelineCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineCountRequest proto.InternalMessageInfo

type GetPipelineCountReply struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelineCountReply) Reset()         { *m = GetPipelineCountReply{} }
func (m *GetPipelineCountReply) String() string { return proto.CompactTextString(m) }
func (*GetPipelineCountReply) ProtoMessage()    {}
func (*GetPipelineCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{3}
}

func (m *GetPipelineCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelineCountReply.Unmarshal(m, b)
}
func (m *GetPipelineCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelineCountReply.Marshal(b, m, deterministic)
}
func (m *GetPipelineCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineCountReply.Merge(m, src)
}
func (m *GetPipelineCountReply) XXX_Size() int {
	return xxx_messageInfo_GetPipelineCountReply.Size(m)
}
func (m *GetPipelineCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineCountReply proto.InternalMessageInfo

func (m *GetPipelineCountReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RegisterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type RegisterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{5}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type UnregisterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterRequest) Reset()         { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()    {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{6}
}

func (m *UnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRequest.Unmarshal(m, b)
}
func (m *UnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRequest.Merge(m, src)
}
func (m *UnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterRequest.Size(m)
}
func (m *UnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRequest proto.InternalMessageInfo

func (m *UnregisterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type UnregisterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterReply) Reset()         { *m = UnregisterReply{} }
func (m *UnregisterReply) String() string { return proto.CompactTextString(m) }
func (*UnregisterReply) ProtoMessage()    {}
func (*UnregisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{7}
}

func (m *UnregisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterReply.Unmarshal(m, b)
}
func (m *UnregisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterReply.Marshal(b, m, deterministic)
}
func (m *UnregisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterReply.Merge(m, src)
}
func (m *UnregisterReply) XXX_Size() int {
	return xxx_messageInfo_UnregisterReply.Size(m)
}
func (m *UnregisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterReply proto.InternalMessageInfo

func (m *UnregisterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UnregisterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ReleasePipelinesRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Pipelines            []uint64 `protobuf:"varint,2,rep,packed,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasePipelinesRequest) Reset()         { *m = ReleasePipelinesRequest{} }
func (m *ReleasePipelinesRequest) String() string { return proto.CompactTextString(m) }
func (*ReleasePipelinesRequest) ProtoMessage()    {}
func (*ReleasePipelinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{8}
}

func (m *ReleasePipelinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasePipelinesRequest.Unmarshal(m, b)
}
func (m *ReleasePipelinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasePipelinesRequest.Marshal(b, m, deterministic)
}
func (m *ReleasePipelinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasePipelinesRequest.Merge(m, src)
}
func (m *ReleasePipelinesRequest) XXX_Size() int {
	return xxx_messageInfo_ReleasePipelinesRequest.Size(m)
}
func (m *ReleasePipelinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasePipelinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasePipelinesRequest proto.InternalMessageInfo

func (m *ReleasePipelinesRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ReleasePipelinesRequest) GetPipelines() []uint64 {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type ReleasePipelinesReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Failures             []uint64 `protobuf:"varint,3,rep,packed,name=failures,proto3" json:"failures,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleasePipelinesReply) Reset()         { *m = ReleasePipelinesReply{} }
func (m *ReleasePipelinesReply) String() string { return proto.CompactTextString(m) }
func (*ReleasePipelinesReply) ProtoMessage()    {}
func (*ReleasePipelinesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{9}
}

func (m *ReleasePipelinesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleasePipelinesReply.Unmarshal(m, b)
}
func (m *ReleasePipelinesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleasePipelinesReply.Marshal(b, m, deterministic)
}
func (m *ReleasePipelinesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleasePipelinesReply.Merge(m, src)
}
func (m *ReleasePipelinesReply) XXX_Size() int {
	return xxx_messageInfo_ReleasePipelinesReply.Size(m)
}
func (m *ReleasePipelinesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleasePipelinesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReleasePipelinesReply proto.InternalMessageInfo

func (m *ReleasePipelinesReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReleasePipelinesReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ReleasePipelinesReply) GetFailures() []uint64 {
	if m != nil {
		return m.Failures
	}
	return nil
}

type GetPipelinesRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelinesRequest) Reset()         { *m = GetPipelinesRequest{} }
func (m *GetPipelinesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPipelinesRequest) ProtoMessage()    {}
func (*GetPipelinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{10}
}

func (m *GetPipelinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelinesRequest.Unmarshal(m, b)
}
func (m *GetPipelinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelinesRequest.Marshal(b, m, deterministic)
}
func (m *GetPipelinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelinesRequest.Merge(m, src)
}
func (m *GetPipelinesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPipelinesRequest.Size(m)
}
func (m *GetPipelinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelinesRequest proto.InternalMessageInfo

func (m *GetPipelinesRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type GetPipelinesReply struct {
	Pipelines            []uint64 `protobuf:"varint,1,rep,packed,name=pipelines,proto3" json:"pipelines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPipelinesReply) Reset()         { *m = GetPipelinesReply{} }
func (m *GetPipelinesReply) String() string { return proto.CompactTextString(m) }
func (*GetPipelinesReply) ProtoMessage()    {}
func (*GetPipelinesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{11}
}

func (m *GetPipelinesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPipelinesReply.Unmarshal(m, b)
}
func (m *GetPipelinesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPipelinesReply.Marshal(b, m, deterministic)
}
func (m *GetPipelinesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelinesReply.Merge(m, src)
}
func (m *GetPipelinesReply) XXX_Size() int {
	return xxx_messageInfo_GetPipelinesReply.Size(m)
}
func (m *GetPipelinesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelinesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelinesReply proto.InternalMessageInfo

func (m *GetPipelinesReply) GetPipelines() []uint64 {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type RegisterAdapterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAdapterRequest) Reset()         { *m = RegisterAdapterRequest{} }
func (m *RegisterAdapterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAdapterRequest) ProtoMessage()    {}
func (*RegisterAdapterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{12}
}

func (m *RegisterAdapterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAdapterRequest.Unmarshal(m, b)
}
func (m *RegisterAdapterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAdapterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAdapterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAdapterRequest.Merge(m, src)
}
func (m *RegisterAdapterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAdapterRequest.Size(m)
}
func (m *RegisterAdapterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAdapterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAdapterRequest proto.InternalMessageInfo

func (m *RegisterAdapterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RegisterAdapterRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RegisterAdapterRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type RegisterAdapterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAdapterReply) Reset()         { *m = RegisterAdapterReply{} }
func (m *RegisterAdapterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterAdapterReply) ProtoMessage()    {}
func (*RegisterAdapterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{13}
}

func (m *RegisterAdapterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAdapterReply.Unmarshal(m, b)
}
func (m *RegisterAdapterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAdapterReply.Marshal(b, m, deterministic)
}
func (m *RegisterAdapterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAdapterReply.Merge(m, src)
}
func (m *RegisterAdapterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterAdapterReply.Size(m)
}
func (m *RegisterAdapterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAdapterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAdapterReply proto.InternalMessageInfo

func (m *RegisterAdapterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterAdapterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type UnregisterAdapterRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterAdapterRequest) Reset()         { *m = UnregisterAdapterRequest{} }
func (m *UnregisterAdapterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterAdapterRequest) ProtoMessage()    {}
func (*UnregisterAdapterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{14}
}

func (m *UnregisterAdapterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterAdapterRequest.Unmarshal(m, b)
}
func (m *UnregisterAdapterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterAdapterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterAdapterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterAdapterRequest.Merge(m, src)
}
func (m *UnregisterAdapterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterAdapterRequest.Size(m)
}
func (m *UnregisterAdapterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterAdapterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterAdapterRequest proto.InternalMessageInfo

func (m *UnregisterAdapterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type UnregisterAdapterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterAdapterReply) Reset()         { *m = UnregisterAdapterReply{} }
func (m *UnregisterAdapterReply) String() string { return proto.CompactTextString(m) }
func (*UnregisterAdapterReply) ProtoMessage()    {}
func (*UnregisterAdapterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{15}
}

func (m *UnregisterAdapterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterAdapterReply.Unmarshal(m, b)
}
func (m *UnregisterAdapterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterAdapterReply.Marshal(b, m, deterministic)
}
func (m *UnregisterAdapterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterAdapterReply.Merge(m, src)
}
func (m *UnregisterAdapterReply) XXX_Size() int {
	return xxx_messageInfo_UnregisterAdapterReply.Size(m)
}
func (m *UnregisterAdapterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterAdapterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterAdapterReply proto.InternalMessageInfo

func (m *UnregisterAdapterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UnregisterAdapterReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*GetClientCountRequest)(nil), "gravity.api.controller.GetClientCountRequest")
	proto.RegisterType((*GetClientCountReply)(nil), "gravity.api.controller.GetClientCountReply")
	proto.RegisterType((*GetPipelineCountRequest)(nil), "gravity.api.controller.GetPipelineCountRequest")
	proto.RegisterType((*GetPipelineCountReply)(nil), "gravity.api.controller.GetPipelineCountReply")
	proto.RegisterType((*RegisterRequest)(nil), "gravity.api.controller.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "gravity.api.controller.RegisterReply")
	proto.RegisterType((*UnregisterRequest)(nil), "gravity.api.controller.UnregisterRequest")
	proto.RegisterType((*UnregisterReply)(nil), "gravity.api.controller.UnregisterReply")
	proto.RegisterType((*ReleasePipelinesRequest)(nil), "gravity.api.controller.ReleasePipelinesRequest")
	proto.RegisterType((*ReleasePipelinesReply)(nil), "gravity.api.controller.ReleasePipelinesReply")
	proto.RegisterType((*GetPipelinesRequest)(nil), "gravity.api.controller.GetPipelinesRequest")
	proto.RegisterType((*GetPipelinesReply)(nil), "gravity.api.controller.GetPipelinesReply")
	proto.RegisterType((*RegisterAdapterRequest)(nil), "gravity.api.controller.RegisterAdapterRequest")
	proto.RegisterType((*RegisterAdapterReply)(nil), "gravity.api.controller.RegisterAdapterReply")
	proto.RegisterType((*UnregisterAdapterRequest)(nil), "gravity.api.controller.UnregisterAdapterRequest")
	proto.RegisterType((*UnregisterAdapterReply)(nil), "gravity.api.controller.UnregisterAdapterReply")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0x5e, 0x97, 0xb1, 0x75, 0x27, 0x60, 0x9d, 0xd9, 0xda, 0x10, 0xf1, 0x50, 0x59, 0x42, 0xeb,
	0x54, 0x9a, 0x31, 0x90, 0x78, 0x9f, 0x8a, 0x34, 0xe0, 0x09, 0x19, 0xf1, 0x86, 0x90, 0xb2, 0x70,
	0x1d, 0x91, 0xac, 0x24, 0xb3, 0x1d, 0x50, 0xdf, 0xf8, 0xd3, 0x51, 0x9c, 0x5f, 0x4d, 0x9a, 0xac,
	0x6e, 0xdf, 0x7a, 0xf5, 0x77, 0xdf, 0x77, 0xbe, 0xf3, 0x7d, 0x81, 0x81, 0x1f, 0x85, 0x4a, 0x44,
	0x9c, 0xa3, 0x70, 0x63, 0x11, 0xa9, 0x88, 0x0c, 0xef, 0x85, 0xf7, 0x27, 0x50, 0x4b, 0xd7, 0x8b,
	0x03, 0xb7, 0x3a, 0xa5, 0x23, 0x38, 0xbf, 0x45, 0x35, 0xe7, 0x01, 0x86, 0x6a, 0x1e, 0x25, 0xa1,
	0x62, 0xf8, 0x90, 0xa0, 0x54, 0x74, 0x0a, 0x2f, 0x9a, 0x07, 0x31, 0x5f, 0x92, 0x33, 0x78, 0xe2,
	0xa7, 0x91, 0xdd, 0x1b, 0xf7, 0x26, 0x07, 0x2c, 0x0b, 0xe8, 0x4b, 0x18, 0xdd, 0xa2, 0xfa, 0x1a,
	0xc4, 0xc8, 0x83, 0x10, 0x6b, 0x3c, 0x33, 0x2d, 0xd0, 0x38, 0xea, 0x66, 0x9a, 0xc1, 0x09, 0xc3,
	0xfb, 0x40, 0x2a, 0x14, 0x39, 0x03, 0x71, 0xa0, 0xef, 0xeb, 0x32, 0x3e, 0x7f, 0xd4, 0xd8, 0x63,
	0x56, 0xc6, 0xf4, 0x06, 0x9e, 0x55, 0xf0, 0x94, 0xd5, 0x86, 0x23, 0x99, 0xf8, 0x3e, 0x4a, 0xa9,
	0xb1, 0x7d, 0x56, 0x84, 0x64, 0x08, 0x87, 0x02, 0x3d, 0x19, 0x85, 0xf6, 0xbe, 0x26, 0xc9, 0x23,
	0x7a, 0x05, 0xa7, 0xdf, 0x43, 0xb1, 0x85, 0xe6, 0x1c, 0x4e, 0x56, 0x13, 0x76, 0x53, 0xfd, 0x06,
	0x23, 0x86, 0x1c, 0x3d, 0x89, 0x45, 0x6b, 0xa4, 0x81, 0x36, 0x79, 0x05, 0xc7, 0x71, 0x81, 0xb7,
	0xf7, 0xc7, 0xd6, 0xe4, 0x80, 0x55, 0x7f, 0x50, 0x84, 0xf3, 0x75, 0xd2, 0x9d, 0xea, 0x4b, 0x8b,
	0x58, 0x78, 0x01, 0x4f, 0x04, 0x4a, 0xdb, 0xd2, 0x3a, 0x65, 0x4c, 0xaf, 0xf5, 0xd3, 0xd8, 0xa6,
	0x6e, 0x7a, 0x0d, 0xa7, 0xf5, 0x94, 0xb4, 0xaa, 0xda, 0x65, 0x7a, 0xcd, 0xcb, 0xfc, 0x84, 0x61,
	0x31, 0xda, 0x9b, 0x5f, 0x5e, 0x6c, 0x36, 0x1c, 0x32, 0x00, 0x2b, 0x11, 0x3c, 0xbf, 0x4c, 0xfa,
	0x33, 0xbd, 0x61, 0xb4, 0x58, 0x48, 0x54, 0xb6, 0x35, 0xee, 0x4d, 0x2c, 0x96, 0x47, 0xf4, 0x13,
	0x9c, 0xad, 0xf1, 0xef, 0x36, 0xcb, 0x0f, 0x60, 0x57, 0x0f, 0xc2, 0xbc, 0x56, 0xfa, 0x05, 0x86,
	0x2d, 0x79, 0x3b, 0xd5, 0xf0, 0xee, 0xdf, 0x11, 0xc0, 0xbc, 0x5c, 0x6b, 0x12, 0xc2, 0xf3, 0xfa,
	0xf6, 0x92, 0x99, 0xdb, 0xee, 0x00, 0x6e, 0xeb, 0xfa, 0x3b, 0x53, 0x53, 0x78, 0xcc, 0x97, 0x74,
	0x8f, 0x28, 0x18, 0x34, 0xb7, 0x9c, 0x5c, 0x3d, 0x42, 0xd1, 0x66, 0x15, 0xce, 0xcc, 0x3c, 0x21,
	0x53, 0xfd, 0x01, 0xfd, 0x62, 0x84, 0xe4, 0xa2, 0x2b, 0xb9, 0x61, 0x27, 0xce, 0xeb, 0xcd, 0xc0,
	0x8c, 0xfd, 0x0e, 0xa0, 0x1a, 0x0f, 0xb9, 0xec, 0x4a, 0x5b, 0x33, 0x0f, 0xe7, 0xc2, 0x04, 0x5a,
	0xf6, 0xad, 0xb9, 0xb1, 0xdd, 0x7d, 0xeb, 0x30, 0x8c, 0xee, 0xbe, 0xb5, 0x9a, 0x01, 0xdd, 0x23,
	0xbf, 0xe1, 0xe9, 0xea, 0x36, 0x92, 0xa9, 0x41, 0xe3, 0x4b, 0xb5, 0x4b, 0x33, 0x70, 0xa6, 0xf4,
	0x50, 0xd9, 0x79, 0xfe, 0xc0, 0x89, 0xbb, 0xa9, 0xff, 0xf5, 0x0d, 0x72, 0xde, 0x18, 0xe3, 0x33,
	0xc9, 0xbf, 0xab, 0x7e, 0x5e, 0x88, 0xbe, 0xdd, 0x3c, 0x92, 0x86, 0xac, 0xbb, 0x45, 0x86, 0x16,
	0xbe, 0x3b, 0xd4, 0x5f, 0xda, 0xf7, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x26, 0x90, 0xb3, 0xbb,
	0x7d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	GetClientCount(ctx context.Context, in *GetClientCountRequest, opts ...grpc.CallOption) (*GetClientCountReply, error)
	GetPipelineCount(ctx context.Context, in *GetPipelineCountRequest, opts ...grpc.CallOption) (*GetPipelineCountReply, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterReply, error)
	ReleasePipelines(ctx context.Context, in *ReleasePipelinesRequest, opts ...grpc.CallOption) (*ReleasePipelinesReply, error)
	GetPipelines(ctx context.Context, in *GetPipelinesRequest, opts ...grpc.CallOption) (*GetPipelinesReply, error)
	RegisterAdapter(ctx context.Context, in *RegisterAdapterRequest, opts ...grpc.CallOption) (*RegisterAdapterReply, error)
	UnregisterAdapter(ctx context.Context, in *UnregisterAdapterRequest, opts ...grpc.CallOption) (*UnregisterAdapterReply, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) GetClientCount(ctx context.Context, in *GetClientCountRequest, opts ...grpc.CallOption) (*GetClientCountReply, error) {
	out := new(GetClientCountReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/GetClientCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetPipelineCount(ctx context.Context, in *GetPipelineCountRequest, opts ...grpc.CallOption) (*GetPipelineCountReply, error) {
	out := new(GetPipelineCountReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/GetPipelineCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterReply, error) {
	out := new(UnregisterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ReleasePipelines(ctx context.Context, in *ReleasePipelinesRequest, opts ...grpc.CallOption) (*ReleasePipelinesReply, error) {
	out := new(ReleasePipelinesReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/ReleasePipelines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetPipelines(ctx context.Context, in *GetPipelinesRequest, opts ...grpc.CallOption) (*GetPipelinesReply, error) {
	out := new(GetPipelinesReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/GetPipelines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RegisterAdapter(ctx context.Context, in *RegisterAdapterRequest, opts ...grpc.CallOption) (*RegisterAdapterReply, error) {
	out := new(RegisterAdapterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/RegisterAdapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UnregisterAdapter(ctx context.Context, in *UnregisterAdapterRequest, opts ...grpc.CallOption) (*UnregisterAdapterReply, error) {
	out := new(UnregisterAdapterReply)
	err := c.cc.Invoke(ctx, "/gravity.api.controller.Controller/UnregisterAdapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	GetClientCount(context.Context, *GetClientCountRequest) (*GetClientCountReply, error)
	GetPipelineCount(context.Context, *GetPipelineCountRequest) (*GetPipelineCountReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Unregister(context.Context, *UnregisterRequest) (*UnregisterReply, error)
	ReleasePipelines(context.Context, *ReleasePipelinesRequest) (*ReleasePipelinesReply, error)
	GetPipelines(context.Context, *GetPipelinesRequest) (*GetPipelinesReply, error)
	RegisterAdapter(context.Context, *RegisterAdapterRequest) (*RegisterAdapterReply, error)
	UnregisterAdapter(context.Context, *UnregisterAdapterRequest) (*UnregisterAdapterReply, error)
}

// UnimplementedControllerServer can be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (*UnimplementedControllerServer) GetClientCount(ctx context.Context, req *GetClientCountRequest) (*GetClientCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientCount not implemented")
}
func (*UnimplementedControllerServer) GetPipelineCount(ctx context.Context, req *GetPipelineCountRequest) (*GetPipelineCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelineCount not implemented")
}
func (*UnimplementedControllerServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedControllerServer) Unregister(ctx context.Context, req *UnregisterRequest) (*UnregisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (*UnimplementedControllerServer) ReleasePipelines(ctx context.Context, req *ReleasePipelinesRequest) (*ReleasePipelinesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleasePipelines not implemented")
}
func (*UnimplementedControllerServer) GetPipelines(ctx context.Context, req *GetPipelinesRequest) (*GetPipelinesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPipelines not implemented")
}
func (*UnimplementedControllerServer) RegisterAdapter(ctx context.Context, req *RegisterAdapterRequest) (*RegisterAdapterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAdapter not implemented")
}
func (*UnimplementedControllerServer) UnregisterAdapter(ctx context.Context, req *UnregisterAdapterRequest) (*UnregisterAdapterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterAdapter not implemented")
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_GetClientCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetClientCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/GetClientCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetClientCount(ctx, req.(*GetClientCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetPipelineCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetPipelineCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/GetPipelineCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetPipelineCount(ctx, req.(*GetPipelineCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ReleasePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ReleasePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/ReleasePipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ReleasePipelines(ctx, req.(*ReleasePipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/GetPipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetPipelines(ctx, req.(*GetPipelinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RegisterAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RegisterAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/RegisterAdapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RegisterAdapter(ctx, req.(*RegisterAdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UnregisterAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterAdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UnregisterAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.api.controller.Controller/UnregisterAdapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UnregisterAdapter(ctx, req.(*UnregisterAdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.api.controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientCount",
			Handler:    _Controller_GetClientCount_Handler,
		},
		{
			MethodName: "GetPipelineCount",
			Handler:    _Controller_GetPipelineCount_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Controller_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Controller_Unregister_Handler,
		},
		{
			MethodName: "ReleasePipelines",
			Handler:    _Controller_ReleasePipelines_Handler,
		},
		{
			MethodName: "GetPipelines",
			Handler:    _Controller_GetPipelines_Handler,
		},
		{
			MethodName: "RegisterAdapter",
			Handler:    _Controller_RegisterAdapter_Handler,
		},
		{
			MethodName: "UnregisterAdapter",
			Handler:    _Controller_UnregisterAdapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
