// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subscriber_manager.proto

package gravity_api_subscriber_manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscriberType int32

const (
	SubscriberType_TRANSMITTER SubscriberType = 0
	SubscriberType_EXPORTER    SubscriberType = 1
)

var SubscriberType_name = map[int32]string{
	0: "TRANSMITTER",
	1: "EXPORTER",
}

var SubscriberType_value = map[string]int32{
	"TRANSMITTER": 0,
	"EXPORTER":    1,
}

func (x SubscriberType) String() string {
	return proto.EnumName(SubscriberType_name, int32(x))
}

func (SubscriberType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{0}
}

type RegisterSubscriberRequest struct {
	SubscriberID         string         `protobuf:"bytes,1,opt,name=subscriberID,proto3" json:"subscriberID,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 SubscriberType `protobuf:"varint,3,opt,name=type,proto3,enum=gravity.api.subscriber_manager.SubscriberType" json:"type,omitempty"`
	Component            string         `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegisterSubscriberRequest) Reset()         { *m = RegisterSubscriberRequest{} }
func (m *RegisterSubscriberRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterSubscriberRequest) ProtoMessage()    {}
func (*RegisterSubscriberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{0}
}

func (m *RegisterSubscriberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSubscriberRequest.Unmarshal(m, b)
}
func (m *RegisterSubscriberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSubscriberRequest.Marshal(b, m, deterministic)
}
func (m *RegisterSubscriberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSubscriberRequest.Merge(m, src)
}
func (m *RegisterSubscriberRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterSubscriberRequest.Size(m)
}
func (m *RegisterSubscriberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSubscriberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSubscriberRequest proto.InternalMessageInfo

func (m *RegisterSubscriberRequest) GetSubscriberID() string {
	if m != nil {
		return m.SubscriberID
	}
	return ""
}

func (m *RegisterSubscriberRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterSubscriberRequest) GetType() SubscriberType {
	if m != nil {
		return m.Type
	}
	return SubscriberType_TRANSMITTER
}

func (m *RegisterSubscriberRequest) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

type RegisterSubscriberReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterSubscriberReply) Reset()         { *m = RegisterSubscriberReply{} }
func (m *RegisterSubscriberReply) String() string { return proto.CompactTextString(m) }
func (*RegisterSubscriberReply) ProtoMessage()    {}
func (*RegisterSubscriberReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{1}
}

func (m *RegisterSubscriberReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterSubscriberReply.Unmarshal(m, b)
}
func (m *RegisterSubscriberReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterSubscriberReply.Marshal(b, m, deterministic)
}
func (m *RegisterSubscriberReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterSubscriberReply.Merge(m, src)
}
func (m *RegisterSubscriberReply) XXX_Size() int {
	return xxx_messageInfo_RegisterSubscriberReply.Size(m)
}
func (m *RegisterSubscriberReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterSubscriberReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterSubscriberReply proto.InternalMessageInfo

func (m *RegisterSubscriberReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterSubscriberReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type UnregisterSubscriberRequest struct {
	SubscriberID         string   `protobuf:"bytes,1,opt,name=subscriberID,proto3" json:"subscriberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterSubscriberRequest) Reset()         { *m = UnregisterSubscriberRequest{} }
func (m *UnregisterSubscriberRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterSubscriberRequest) ProtoMessage()    {}
func (*UnregisterSubscriberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{2}
}

func (m *UnregisterSubscriberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterSubscriberRequest.Unmarshal(m, b)
}
func (m *UnregisterSubscriberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterSubscriberRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterSubscriberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterSubscriberRequest.Merge(m, src)
}
func (m *UnregisterSubscriberRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterSubscriberRequest.Size(m)
}
func (m *UnregisterSubscriberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterSubscriberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterSubscriberRequest proto.InternalMessageInfo

func (m *UnregisterSubscriberRequest) GetSubscriberID() string {
	if m != nil {
		return m.SubscriberID
	}
	return ""
}

type UnregisterSubscriberReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterSubscriberReply) Reset()         { *m = UnregisterSubscriberReply{} }
func (m *UnregisterSubscriberReply) String() string { return proto.CompactTextString(m) }
func (*UnregisterSubscriberReply) ProtoMessage()    {}
func (*UnregisterSubscriberReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{3}
}

func (m *UnregisterSubscriberReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterSubscriberReply.Unmarshal(m, b)
}
func (m *UnregisterSubscriberReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterSubscriberReply.Marshal(b, m, deterministic)
}
func (m *UnregisterSubscriberReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterSubscriberReply.Merge(m, src)
}
func (m *UnregisterSubscriberReply) XXX_Size() int {
	return xxx_messageInfo_UnregisterSubscriberReply.Size(m)
}
func (m *UnregisterSubscriberReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterSubscriberReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterSubscriberReply proto.InternalMessageInfo

func (m *UnregisterSubscriberReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UnregisterSubscriberReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HealthCheckRequest struct {
	SubscriberID         string   `protobuf:"bytes,1,opt,name=subscriberID,proto3" json:"subscriberID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{4}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetSubscriberID() string {
	if m != nil {
		return m.SubscriberID
	}
	return ""
}

type HealthCheckReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReply) Reset()         { *m = HealthCheckReply{} }
func (m *HealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReply) ProtoMessage()    {}
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{5}
}

func (m *HealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReply.Unmarshal(m, b)
}
func (m *HealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReply.Marshal(b, m, deterministic)
}
func (m *HealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReply.Merge(m, src)
}
func (m *HealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReply.Size(m)
}
func (m *HealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReply proto.InternalMessageInfo

func (m *HealthCheckReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *HealthCheckReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Subscriber struct {
	SubscriberID         string               `protobuf:"bytes,1,opt,name=subscriberID,proto3" json:"subscriberID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 SubscriberType       `protobuf:"varint,3,opt,name=type,proto3,enum=gravity.api.subscriber_manager.SubscriberType" json:"type,omitempty"`
	Component            string               `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	LastCheck            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastCheck,proto3" json:"lastCheck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Subscriber) Reset()         { *m = Subscriber{} }
func (m *Subscriber) String() string { return proto.CompactTextString(m) }
func (*Subscriber) ProtoMessage()    {}
func (*Subscriber) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{6}
}

func (m *Subscriber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscriber.Unmarshal(m, b)
}
func (m *Subscriber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscriber.Marshal(b, m, deterministic)
}
func (m *Subscriber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscriber.Merge(m, src)
}
func (m *Subscriber) XXX_Size() int {
	return xxx_messageInfo_Subscriber.Size(m)
}
func (m *Subscriber) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscriber.DiscardUnknown(m)
}

var xxx_messageInfo_Subscriber proto.InternalMessageInfo

func (m *Subscriber) GetSubscriberID() string {
	if m != nil {
		return m.SubscriberID
	}
	return ""
}

func (m *Subscriber) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Subscriber) GetType() SubscriberType {
	if m != nil {
		return m.Type
	}
	return SubscriberType_TRANSMITTER
}

func (m *Subscriber) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *Subscriber) GetLastCheck() *timestamp.Timestamp {
	if m != nil {
		return m.LastCheck
	}
	return nil
}

type GetSubscribersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscribersRequest) Reset()         { *m = GetSubscribersRequest{} }
func (m *GetSubscribersRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubscribersRequest) ProtoMessage()    {}
func (*GetSubscribersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{7}
}

func (m *GetSubscribersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscribersRequest.Unmarshal(m, b)
}
func (m *GetSubscribersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscribersRequest.Marshal(b, m, deterministic)
}
func (m *GetSubscribersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscribersRequest.Merge(m, src)
}
func (m *GetSubscribersRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubscribersRequest.Size(m)
}
func (m *GetSubscribersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscribersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscribersRequest proto.InternalMessageInfo

type GetSubscribersReply struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string        `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Subscribers          []*Subscriber `protobuf:"bytes,3,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSubscribersReply) Reset()         { *m = GetSubscribersReply{} }
func (m *GetSubscribersReply) String() string { return proto.CompactTextString(m) }
func (*GetSubscribersReply) ProtoMessage()    {}
func (*GetSubscribersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{8}
}

func (m *GetSubscribersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscribersReply.Unmarshal(m, b)
}
func (m *GetSubscribersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscribersReply.Marshal(b, m, deterministic)
}
func (m *GetSubscribersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscribersReply.Merge(m, src)
}
func (m *GetSubscribersReply) XXX_Size() int {
	return xxx_messageInfo_GetSubscribersReply.Size(m)
}
func (m *GetSubscribersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscribersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscribersReply proto.InternalMessageInfo

func (m *GetSubscribersReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetSubscribersReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *GetSubscribersReply) GetSubscribers() []*Subscriber {
	if m != nil {
		return m.Subscribers
	}
	return nil
}

type SubscribeToCollectionsRequest struct {
	SubscriberID         string   `protobuf:"bytes,1,opt,name=subscriberID,proto3" json:"subscriberID,omitempty"`
	Collections          []string `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToCollectionsRequest) Reset()         { *m = SubscribeToCollectionsRequest{} }
func (m *SubscribeToCollectionsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToCollectionsRequest) ProtoMessage()    {}
func (*SubscribeToCollectionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{9}
}

func (m *SubscribeToCollectionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToCollectionsRequest.Unmarshal(m, b)
}
func (m *SubscribeToCollectionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToCollectionsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeToCollectionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToCollectionsRequest.Merge(m, src)
}
func (m *SubscribeToCollectionsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToCollectionsRequest.Size(m)
}
func (m *SubscribeToCollectionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToCollectionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToCollectionsRequest proto.InternalMessageInfo

func (m *SubscribeToCollectionsRequest) GetSubscriberID() string {
	if m != nil {
		return m.SubscriberID
	}
	return ""
}

func (m *SubscribeToCollectionsRequest) GetCollections() []string {
	if m != nil {
		return m.Collections
	}
	return nil
}

type SubscribeToCollectionsReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Collections          []string `protobuf:"bytes,3,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToCollectionsReply) Reset()         { *m = SubscribeToCollectionsReply{} }
func (m *SubscribeToCollectionsReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeToCollectionsReply) ProtoMessage()    {}
func (*SubscribeToCollectionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a034a3c281348446, []int{10}
}

func (m *SubscribeToCollectionsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToCollectionsReply.Unmarshal(m, b)
}
func (m *SubscribeToCollectionsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToCollectionsReply.Marshal(b, m, deterministic)
}
func (m *SubscribeToCollectionsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToCollectionsReply.Merge(m, src)
}
func (m *SubscribeToCollectionsReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeToCollectionsReply.Size(m)
}
func (m *SubscribeToCollectionsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToCollectionsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToCollectionsReply proto.InternalMessageInfo

func (m *SubscribeToCollectionsReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SubscribeToCollectionsReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SubscribeToCollectionsReply) GetCollections() []string {
	if m != nil {
		return m.Collections
	}
	return nil
}

func init() {
	proto.RegisterEnum("gravity.api.subscriber_manager.SubscriberType", SubscriberType_name, SubscriberType_value)
	proto.RegisterType((*RegisterSubscriberRequest)(nil), "gravity.api.subscriber_manager.RegisterSubscriberRequest")
	proto.RegisterType((*RegisterSubscriberReply)(nil), "gravity.api.subscriber_manager.RegisterSubscriberReply")
	proto.RegisterType((*UnregisterSubscriberRequest)(nil), "gravity.api.subscriber_manager.UnregisterSubscriberRequest")
	proto.RegisterType((*UnregisterSubscriberReply)(nil), "gravity.api.subscriber_manager.UnregisterSubscriberReply")
	proto.RegisterType((*HealthCheckRequest)(nil), "gravity.api.subscriber_manager.HealthCheckRequest")
	proto.RegisterType((*HealthCheckReply)(nil), "gravity.api.subscriber_manager.HealthCheckReply")
	proto.RegisterType((*Subscriber)(nil), "gravity.api.subscriber_manager.Subscriber")
	proto.RegisterType((*GetSubscribersRequest)(nil), "gravity.api.subscriber_manager.GetSubscribersRequest")
	proto.RegisterType((*GetSubscribersReply)(nil), "gravity.api.subscriber_manager.GetSubscribersReply")
	proto.RegisterType((*SubscribeToCollectionsRequest)(nil), "gravity.api.subscriber_manager.SubscribeToCollectionsRequest")
	proto.RegisterType((*SubscribeToCollectionsReply)(nil), "gravity.api.subscriber_manager.SubscribeToCollectionsReply")
}

func init() { proto.RegisterFile("subscriber_manager.proto", fileDescriptor_a034a3c281348446) }

var fileDescriptor_a034a3c281348446 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0x76, 0xe8, 0x8a, 0xec, 0x29, 0x41, 0x32, 0x46, 0x19, 0xc0, 0x9f, 0x66, 0xae, 0x1a, 0x2e,
	0x66, 0x93, 0xf5, 0x86, 0x5b, 0x04, 0xa2, 0x44, 0x51, 0x33, 0xd4, 0xc4, 0x3b, 0x33, 0xdb, 0x1c,
	0x4b, 0x63, 0xdb, 0x29, 0x33, 0xb3, 0x26, 0x7d, 0x10, 0x1f, 0xc5, 0xf7, 0xf1, 0x51, 0x8c, 0xc3,
	0x2e, 0xc3, 0x02, 0x1a, 0xa9, 0x37, 0xde, 0xf5, 0xfc, 0x7c, 0xe7, 0xfb, 0xce, 0x37, 0xa7, 0xc0,
	0xec, 0x74, 0x62, 0x73, 0x53, 0x4e, 0xd0, 0x7c, 0xaa, 0x55, 0xa3, 0x0a, 0x34, 0xa2, 0x35, 0xda,
	0x69, 0xfa, 0xb4, 0x30, 0xea, 0x6b, 0xe9, 0x3a, 0xa1, 0xda, 0x52, 0x5c, 0xef, 0xda, 0x7a, 0x56,
	0x68, 0x5d, 0x54, 0x38, 0xf2, 0xdd, 0x93, 0xe9, 0xe7, 0x91, 0x2b, 0x6b, 0xb4, 0x4e, 0xd5, 0xed,
	0xf9, 0x00, 0xfe, 0x9d, 0xc0, 0xa6, 0xc4, 0xa2, 0xb4, 0x0e, 0xcd, 0xc9, 0x05, 0x5e, 0xe2, 0xd9,
	0x14, 0xad, 0xa3, 0x1c, 0x56, 0xc3, 0xd0, 0xa3, 0x03, 0x46, 0x12, 0x92, 0x0e, 0xe5, 0x42, 0x8e,
	0x52, 0x18, 0x34, 0xaa, 0x46, 0xb6, 0xe4, 0x6b, 0xfe, 0x9b, 0xbe, 0x80, 0x81, 0xeb, 0x5a, 0x64,
	0x51, 0x42, 0xd2, 0xb5, 0xb1, 0x10, 0x7f, 0x56, 0x29, 0x02, 0x71, 0xd6, 0xb5, 0x28, 0x3d, 0x96,
	0x3e, 0x86, 0x61, 0xae, 0xeb, 0x56, 0x37, 0xd8, 0x38, 0x36, 0xf0, 0xc3, 0x43, 0x82, 0xbf, 0x86,
	0x8d, 0x9b, 0x64, 0xb7, 0x55, 0x47, 0x19, 0xdc, 0xb3, 0xd3, 0x3c, 0x47, 0x6b, 0xbd, 0xde, 0x15,
	0x39, 0x0f, 0xe9, 0x23, 0x58, 0x36, 0xa8, 0xac, 0x6e, 0x66, 0x62, 0x67, 0x11, 0xdf, 0x83, 0xed,
	0x0f, 0x8d, 0xf9, 0x17, 0x17, 0xf8, 0x31, 0x6c, 0xde, 0x3c, 0xa2, 0x9f, 0xa2, 0x5d, 0xa0, 0xaf,
	0x50, 0x55, 0xee, 0x74, 0xff, 0x14, 0xf3, 0x2f, 0xb7, 0x11, 0x72, 0x00, 0xeb, 0x0b, 0xc8, 0x7e,
	0xfc, 0x3f, 0x08, 0x40, 0xd8, 0xe2, 0xff, 0xbd, 0x03, 0xba, 0x0b, 0xc3, 0x4a, 0x59, 0xe7, 0x97,
	0x65, 0x77, 0x13, 0x92, 0xc6, 0xe3, 0x2d, 0x71, 0x7e, 0xf4, 0x62, 0x7e, 0xf4, 0x22, 0x9b, 0x1f,
	0xbd, 0x0c, 0xcd, 0x7c, 0x03, 0x1e, 0xbe, 0x44, 0x17, 0x28, 0xed, 0xcc, 0x65, 0xfe, 0x8d, 0xc0,
	0x83, 0xab, 0x95, 0x5e, 0x2e, 0xd2, 0x37, 0x10, 0x87, 0x2d, 0x2d, 0x8b, 0x92, 0x28, 0x8d, 0xc7,
	0x3b, 0x7f, 0xef, 0x82, 0xbc, 0x0c, 0xe7, 0x08, 0x4f, 0x2e, 0x4a, 0x99, 0xde, 0xd7, 0x55, 0x85,
	0xb9, 0x2b, 0x75, 0x63, 0x6f, 0xf3, 0xb7, 0x26, 0x10, 0xe7, 0x01, 0xc9, 0x96, 0x92, 0x28, 0x1d,
	0xca, 0xcb, 0x29, 0x7e, 0x06, 0xdb, 0xbf, 0xa3, 0xe9, 0xe7, 0xc2, 0x15, 0xca, 0xe8, 0x1a, 0xe5,
	0xce, 0x08, 0xd6, 0x16, 0x9f, 0x9e, 0xde, 0x87, 0x38, 0x93, 0x7b, 0x6f, 0x4f, 0x8e, 0x8f, 0xb2,
	0xec, 0x50, 0xae, 0xdf, 0xa1, 0xab, 0xb0, 0x72, 0xf8, 0xf1, 0xfd, 0x3b, 0xf9, 0x2b, 0x22, 0x93,
	0x65, 0xff, 0xb4, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x89, 0xd7, 0x20, 0x19, 0x05,
	0x00, 0x00,
}
