// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline.proto

package gravity_api_pipeline

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PipelineReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineReply) Reset()         { *m = PipelineReply{} }
func (m *PipelineReply) String() string { return proto.CompactTextString(m) }
func (*PipelineReply) ProtoMessage()    {}
func (*PipelineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{0}
}

func (m *PipelineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineReply.Unmarshal(m, b)
}
func (m *PipelineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineReply.Marshal(b, m, deterministic)
}
func (m *PipelineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineReply.Merge(m, src)
}
func (m *PipelineReply) XXX_Size() int {
	return xxx_messageInfo_PipelineReply.Size(m)
}
func (m *PipelineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineReply.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineReply proto.InternalMessageInfo

func (m *PipelineReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PipelineReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*PipelineReply)(nil), "gravity.api.pipeline.PipelineReply")
}

func init() { proto.RegisterFile("pipeline.proto", fileDescriptor_7ac67a7adf3df9c7) }

var fileDescriptor_7ac67a7adf3df9c7 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0x2c, 0x48,
	0xcd, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0x2f, 0x4a, 0x2c,
	0xcb, 0x2c, 0xa9, 0xd4, 0x4b, 0x2c, 0xc8, 0xd4, 0x83, 0xc9, 0x29, 0x39, 0x72, 0xf1, 0x06, 0x40,
	0xd9, 0x41, 0xa9, 0x05, 0x39, 0x95, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5,
	0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x6a,
	0x62, 0x71, 0x7e, 0x9e, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0x97, 0xc4, 0x06, 0x36,
	0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x15, 0x2f, 0xb1, 0x71, 0x00, 0x00, 0x00,
}
